projects:
  - num: 2
    basename: clusterproject
    ifexists: reuse
    tuning: default
    users:
      - num: 2
        role: admin
        basename: demo
        password: demo
        userpassfile: openshift-passwd
    services:
      - num: 1
        file: default
        basename: testservice
    rcs:
      - num: 2
        replicas: 1
        file: default
        basename: testrc
        image: registry.redhat.io/openshift4/ose-hello-openshift-rhel8
    pods:
      - total: 2
      - num: 100
        image: registry.redhat.io/openshift4/ose-hello-openshift-rhel8
        basename: hellopods
        file: default
        storage:
          - type: none 

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 1 s
      rate_limit:
        delay: 250 ms
